---
- name: Setup Red Hat Subscription Allocation
  hosts: redhatconsole
  gather_facts: false
  vars:
    rhsm_subscription_allocation_name: aap
    rhsm_subscription_name: Employee SKU
    rhsm_subscription_entitlement_count: 50
    rhsm_manifest_dest: ./manifest.zip

  tasks:
    # - name: Get subscription allocation info
    #   ansible.builtin.include_role:
    #     name: subscription_allocation

    - name: Get manifest
      ansible.builtin.include_role:
        name: get_manifest
