---
# tasks file for subscription_allocation
- name: Get existing subscription allocations
  ansible.builtin.include_role:
    name: subscription_allocation_info

- name: Check for existing subscription allocation
  ansible.builtin.set_fact:
    rhsm_existing_subscription_allocation: >-
      {{
        rhsm_subscription_allocations['json']['body']
        | selectattr('name', 'match', rhsm_subscription_allocation_name)
      }}

- name: Create subscription allocation
  when: rhsm_existing_subscription_allocation[0] is not defined
  block:
    - name: "Create subscription allocation {{ rhsm_subscription_allocation_name }}"
      ansible.builtin.uri:
        url: "{{ rhsm_base_uri }}/allocations?name={{ rhsm_subscription_allocation_name | urlencode }}&version={{ rhsm_subscription_allocation_satellite_version | urlencode }}" # noqa yaml[line-length]
        method: POST
        headers:
          Authorization: "Bearer {{ rhsm_access_token }}"
          Content-Type: application/json
      register: rhsm_subscription_allocation

- name: Set fact for existing subscription allocation
  when: rhsm_existing_subscription_allocation[0] is defined
  ansible.builtin.set_fact:
    rhsm_subscription_allocation: "{{ rhsm_existing_subscription_allocation[0] }}"

- name: Get available subscriptions
  ansible.builtin.uri:
    url: "{{ rhsm_base_uri }}/subscriptions"
    method: GET
    headers:
      Authorization: "Bearer {{ rhsm_access_token }}"
  register: rhsm_subscriptions

- name: Get existing entitlements
  ansible.builtin.uri:
    url: "{{ rhsm_base_uri }}/allocations/{{ rhsm_subscription_allocation['uuid'] | urlencode }}"
    method: GET
    headers:
      Authorization: "Bearer {{ rhsm_access_token }}"
  register: rhsm_existing_entitlements

- name: Attach desired entitlements
  ansible.builtin.uri:
    url: "{{ rhsm_base_uri }}/allocations/{{ rhsm_subscription_allocation['uuid'] | urlencode }}/entitlements?pool={{ rhsm_desired_subscription_pool_id | urlencode }}&quantity={{ rhsm_subscription_entitlement_count }}" # noqa yaml[line-length]
    method: POST
    headers:
      Authorization: "Bearer {{ rhsm_access_token }}"
      Content-Type: application/json
  vars:
    rhsm_desired_subscription: "{{ (rhsm_subscriptions['json']['body'] | selectattr('subscriptionName', 'match', rhsm_subscription_name))[0] }}"
    rhsm_desired_subscription_pool_id: "{{ rhsm_desired_subscription['pools'][0]['id'] }}"
