---
# tasks file for rhsm_api_token
- name: Get Refresh token
  when: rhsm_api_token_refresh
  block:
    - name: Get Red Hat API access token

      ansible.builtin.uri:
        url: "https://sso.redhat.com/auth/realms/redhat-external/protocol/openid-connect/token"
        method: POST
        body:
          grant_type: refresh_token
          client_id: rhsm-api
          refresh_token: "{{ redhat_api_offline_token | default(lookup('ansible.builtin.env', 'REDHAT_API_OFFLINE_TOKEN')) }}"
        body_format: form-urlencoded
      register: token_request

    - name: Set fact for access token
      ansible.builtin.set_fact:
        rhsm_access_token: "{{ token_request.json.access_token }}"