---
# tasks file for subscription_allocation_info
- name: Refresh RHSM API Token
  ansible.builtin.include_role:
    name: rhsm_api_token
  vars:
    rhsm_api_token_refresh: true

- name: Retrieve current subscription allocations
  ansible.builtin.uri:
    url: "{{ rhsm_base_uri }}/allocations?type=Satellite"
    method: GET
    headers:
      Authorization: "Bearer {{ rhsm_access_token }}"
  register: rhsm_subscription_allocations

- name: Retrieve specific subscription allocations
  when: rhsm_subscription_name is defined
  ansible.builtin.set_fact:
    rhsm_subscription_allocations: >-
      {{
        rhsm_subscription_allocations['json']['body']
        | selectattr('name', 'match', rhsm_subscription_allocation_name)
      }}
